# Description: Installs nodejs from source
#
# Parameters - Must be definied in playbook:
#   - node_path = The nodejs path
#   - node_prefix = The prefix
#   - node_tarball = The tarball filename at nodejs.org
#   - node_version = The wanted version of node to be installed

- name: Checking installed version of node.js
  shell: /usr/bin/test "$(node -v 2> /dev/null)" = v{{ node_version }}
  register: wanted_version_installed
  ignore_errors: True

- name: Fetching node.js source
  action: get_url url=http://nodejs.org/dist/v{{ node_version }}/{{ node_tarball }} dest=/tmp/
  when: wanted_version_installed.rc == 1

- name: Unpack node.js tarball
  command: tar zxf {{ node_tarball }} chdir=/tmp
  when: wanted_version_installed.rc == 1

- name: Configure
  shell: /usr/bin/python ./configure --prefix={{ node_path }} chdir=/tmp/{{ node_prefix }}
  when: wanted_version_installed.rc == 1

- name: Make
  shell: /usr/bin/make chdir=/tmp/{{ node_prefix }}/
  when: wanted_version_installed.rc == 1

- name: Make install
  shell: /usr/bin/make install chdir=/tmp/{{ node_prefix }}/
  when: wanted_version_installed.rc == 1

# install less
- name: ensure some nodejs packages are installed
  npm: name={{ item }} global=yes
  with_items:
    - less