- hosts: all
  sudo: yes

  vars:
  # global vars
    app_name: "simplex"

  # node.js vars
    node_version: "0.10.23"
    node_path: "/usr/local"

  # derived
    node_prefix: "node-v{{ node_version }}"
    node_tarball: "{{ node_prefix }}.tar.gz"

  roles:
    - common
    - nodejs
    - apache
    - mysql
    - php
